data/unity8.conf usr/share/upstart/sessions/
data/unity8-dash.conf usr/share/upstart/sessions/
data/unity8-filewatcher.conf usr/share/upstart/sessions/
usr/bin/unity8
usr/bin/unity8-dash
usr/share/applications/unity8.desktop
usr/share/applications/unity8-dash.desktop
usr/share/unity8/Greeter
usr/share/unity8/Hud
usr/share/unity8/Launcher
usr/share/unity8/Panel
usr/share/unity8/Shell.qml
usr/share/unity8/Stages
