#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2 -*-

# Ensure the shell always gets unthrottled touch events, so that applications
# who want full speed low-latency input can get it (LP: #1497105) and so that
# apps can use QML touch compression safely (the QML touch compression
# algorithm does not support nesting well - LP: #1486341, LP: #1556763 - so
# must be fed by the raw input event stream from Unity8).
export QML_NO_TOUCH_COMPRESSION=1

export MIR_SERVER_PROMPT_FILE=1

# Hard code socket path because our snappy apparmor profile
# only lets us put the socket in one place.  And consumers expect it there.
# (XDG_RUNTIME_DIR isn't typical under snappy)
export MIR_SERVER_FILE=/run/user/$(id -u)/mir_socket

rm -f "$MIR_SERVER_FILE"
rm -f "${MIR_SERVER_FILE}_trusted"

if [ "$XDG_SESSION_DESKTOP" = "ubuntu-touch" ]; then
  # On Ubuntu Touch, we currently use a trick where we auto-login the
  # user without a LightDM greeter at all.  In this case, we want to
  # start with the lockscreen visible.  Once we switch to using a
  # proper greeter for the first login, we can remove this code path.
  MODE=full-greeter
else
  MODE=full-shell
fi

dbus-update-activation-environment --systemd MIR_SOCKET=$MIR_SERVER_FILE

# Tell unity-mir to raise SIGSTOP after we start, which we use to tell
# systemd when we are done starting up.
export UNITY_MIR_EMITS_SIGSTOP=1

${BINARY:-unity8} --mode=$MODE "$@" &
child=$!

count=0
while [ $count -lt 2000 ]; do # 20 seconds
    sleep 0.01
    if [ $(ps --no-headers -o state $child) = "T" ]; then
        kill -CONT $child
        exit 0
    fi
    count=`expr $count + 1`
done

echo "Aborting unity8 launch: didn't hear back from Mir"
exit 100
